#server.port = 8081
#spring.datasource.url = jdbc:mariadb://localhost:3306/member
#spring.datasource.username = root
#spring.datasource.password = 1234

#server:
#  port: 8081

# 필요한 이유: jdbc는 모든 스프링 기술의 근간이다.
spring:
  # controller와 jsp 사용 시에 경로 및 확장자 설정
  # 기본 설정이 Thymeleaf 이므로 의존성 제거해줘야 함
  # Controller의 기본 설정이 Thymeleaf이므로, templates폴더에서 파일을 찾게된다.
  # 하지만, jsp는 webapp폴더에 있으므로 thymeleaf 의존성 제거
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa:
    database: mysql # mariaDB로 하면 에러난다고 함
    # innoDB 엔진 사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    # 테이블 및 컬럼 자동 생성 (단, 스키마는 사전 생성 필요. JPA가 엔티티를 기준으로 테이블을 생성함)
    generate-ddl: true
    # hibernate: JPA의 구현체
    hibernate:
      # create 옵션은 서버를 재부팅할 때마다 table을 매번 drop 후 생성한다.
      # update 옵션은 변경사항만 Alter 적용 (Drop 안시킴)
      # validate는 실제 DB와의 차이만을 Check
      # 실무에서는 update 또는 validate 사용
      ddl-auto: update
    # jpa가 자동으로 쿼리를 생성할 때, 쿼리가 console 창에 보여짐
    show_sql: true

 # Spring Boot 2.4 이상에서는 기본적으로 PathPatternParse를 사용하고 있는데,
  # 이는 이전 버전과 다른 경로 매칭 규칙을 가지고 있고, springfox와 같은 외부 라이브러리에선느 문제 발생
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mapper 파일의 위치
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234
#
#---
#
#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: prod
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234